"""-modif model-post with user_id

Revision ID: 126eea6a8164
Revises: 54ad79dea224
Create Date: 2026-04-18 17:35:29.485122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126eea6a8164'
down_revision = '54ad79dea224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
