"""remove user-about relation

Revision ID: 1880538a7393
Revises: 41d3522e228d
Create Date: 2026-04-18 23:31:38.086568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1880538a7393'
down_revision = '41d3522e228d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('about_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('about_ibfk_1'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
