"""update blog table

Revision ID: 63579ea0120f
Revises: 15c1e1b48bc0
Create Date: 2026-02-17 17:54:48.465969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63579ea0120f'
down_revision = '15c1e1b48bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
